# Generated by Django 2.2.7 on 2019-11-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191130_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=11)),
                ('crm', models.CharField(max_length=11)),
                ('especialidade', models.CharField(max_length=20)),
            ],
        ),
    ]
